### ISSUE TITLE
It would be nice to publish the reference URLs from the book here as well

### ISSUE THREAD

**Issue by MarcSaric** [TheJacksonLaboratory/Computational-Genome-Analysis#4]
Dear authors,

for convenient access to all the URLs listed in the book, it would be good to have a list of links here. I am sure, that this request would not make sense for those people buying the electronic version of the book, where only broken or outdated URLs are of interest. However, for people, who bought the hardcopy (or for people lending a hardcopy from a library), it would be more convenient to just click a link instead of typing a 50 character+ URL from the book text.

Thank you.

**Comment by pnrobinson** [comment]
Thanks for the suggestion -- however, there are so may URLs in the text that it would not make things much easier -- you would need to go from the printed book to this site, search the correct URL, etc. Many users also will want to vary the URLs and related commands.
