### ISSUE TITLE
Book Typo: 4.5 1000 GENOMES WGS DATA: NA12891–SRR622458; mother: NA12892–SRR622458

### ISSUE THREAD

**Issue by snewhouse** [TheJacksonLaboratory/Computational-Genome-Analysis#5]
**4.5 1000 GENOMES WGS DATA**

Original Text: 

>We use a family trio from the 1000 Genomes Project to demonstrate de novo variant calling as well as the CNV callers CNVnator and DELLY. This is thcdataset with the SRA Project Accession PRJNA186949. This project contains samples from the same three individuals as above (daughter: NA12878–SRR622457; father: `NA12891–SRR622458; mother: NA12892–SRR622458`). Down-load the FASTQ ﬁles with the following commands:

**Error**: `NA12891–SRR622458; mother: NA12892–SRR622458` They have the same SRR Id.

**Update this to: NA12892–SRR622459**

>We use a family trio from the 1000 Genomes Project to demonstrate de novo variant calling as well as the CNV callers CNVnator and DELLY. This is thcdataset with the SRA Project Accession PRJNA186949. This project contains samples from the same three individuals as above (daughter: NA12878–SRR622457; father: `NA12891–SRR622458; mother: NA12892–SRR622459`). Down-load the FASTQ ﬁles with the following commands:

**Comment by pnrobinson** [comment]
Thanks for pointing this out and sorry for the late response. I have added this to the Errata page:
https://github.com/TheJacksonLaboratory/Computational-Genome-Analysis/blob/master/ERRATA.md
