### ISSUE TITLE
Book Typo: 9.6 The SAM BITFLAG  page 119

### ISSUE THREAD

**Issue by xiaoledeng** [TheJacksonLaboratory/Computational-Genome-Analysis#6]
$1 \times 2^{5}+0 \times 2^{4}+1 \times 2^{3}+1 \times 2^{2}+0 \times 1^{1}+1 \times 2^{0}=32+8+4+1=45$ 

shoud be revised to 

$1 \times 2^{5}+0 \times 2^{4}+1 \times 2^{3}+1 \times 2^{2}+0 \times 2^{1}+1 \times 2^{0}=32+8+4+1=45$

**Comment by pnrobinson** [comment]
Yes thank you -- Let's put this on the errata

**Comment by pnrobinson** [comment]
thanks a lot for pointing this out! I have updated the Errata page:
https://github.com/TheJacksonLaboratory/Computational-Genome-Analysis/blob/master/ERRATA.md
